// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *

#set page(width: auto, height: auto, margin: 0.9em)

#let axes-0(xlim: (-6.65, 7.65), ylim: (-10.75, 27.75), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let title-center = (
    position: (50.0%, -2.556%),
    body: place(center + bottom, text(size: 1em + 2.0pt, fill: color.rgb("#000000"), [Hello World])),
  )

  let title-right = (
    position: (100.0%, -2.556%),
    body: place(right + bottom, text(size: 1em + 2.0pt, fill: color.rgb("#000000"), [more titles?])),
  )


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let label-xaxis = (
    position: (50.0%, 108.979%),
    body: place(center + top, text(size: 1em, fill: color.rgb("#000000"), [xXlabelXx])),
  )

  let label-yaxis = (
    position: (-8.473%, 50.0%),
    body: rotate(-90.0deg, place(center + bottom, text(
      size: 1em,
      fill: color.rgb("#000000"),
      bottom-edge: "descender",
      [A y-label with an equation $y = x^2$],
    ))),
  )

  let xaxis-major-ticks = (
    locs: (-8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0),
    labels: ($−8$, $−6$, $−4$, $−2$, $0$, $2$, $4$, $6$, $8$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0),
    labels: ($−15$, $−10$, $−5$, $0$, $5$, $10$, $15$, $20$, $25$, $30$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = markers.circle(3.0pt, fill: color.rgb("#1f77b4"), stroke: color.luma(0%) + 1.0pt)
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let fill-collection-1 = ()
  let stroke-collection-1 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let fill-collection-2 = ()
  let stroke-collection-2 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-2 = transform
  let compute-scale-collection-2 = compute-scale
  let offset-transform-collection-2 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-2 = (
    data: data.at("collection-2"),
    fill: fill-collection-2,
    stroke: stroke-collection-2,
    transform: transform-collection-2,
    compute-scale: compute-scale-collection-2,
    offset-transform: offset-transform-collection-2,
  )

  let stroke-line-3 = none
  let marker-line-3 = markers.vline(4.0pt, fill: color.rgb("#1f77b4"), stroke: color.rgb("#1f77b4") + 2pt)
  let line-3 = (data: data.at("line-3"), stroke: stroke-line-3, marker: marker-line-3, transform: transform)

  let stroke-line-4 = none
  let marker-line-4 = markers.vline(4.0pt, fill: color.rgb("#1f77b4"), stroke: color.rgb("#1f77b4") + 2pt)
  let line-4 = (data: data.at("line-4"), stroke: stroke-line-4, marker: marker-line-4, transform: transform)

  let stroke-line-5 = none
  let marker-line-5 = markers.hline(4.0pt, fill: color.rgb("#1f77b4"), stroke: color.rgb("#1f77b4") + 2pt)
  let line-5 = (data: data.at("line-5"), stroke: stroke-line-5, marker: marker-line-5, transform: transform)

  let stroke-line-6 = none
  let marker-line-6 = markers.hline(4.0pt, fill: color.rgb("#1f77b4"), stroke: color.rgb("#1f77b4") + 2pt)
  let line-6 = (data: data.at("line-6"), stroke: stroke-line-6, marker: marker-line-6, transform: transform)

  let stroke-line-7 = (paint: color.rgb("#ff7f0e"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-7 = markers.hexagon1(3.0pt, fill: color.rgb("#ff7f0e"), stroke: color.rgb("#ff7f0e") + 1.0pt)
  let line-7 = (data: data.at("line-7"), stroke: stroke-line-7, marker: marker-line-7, transform: transform)

  let text-8 = (
    position: (5.652%, 22.542%),
    body: place(left + top, text(size: 1em, fill: color.rgb("#000000"), [pass])),
  )

  let text-9 = (
    position: (13.264%, 22.542%),
    body: place(left + horizon, text(size: 1em, fill: color.rgb("#000000"), [pass])),
  )

  let text-10 = (
    position: (20.875%, 22.542%),
    body: place(left + horizon, text(size: 1em, fill: color.rgb("#000000"), bottom-edge: "descender", [pass])),
  )

  let text-11 = (
    position: (28.486%, 22.542%),
    body: place(left + bottom, text(size: 1em, fill: color.rgb("#000000"), [pass])),
  )

  let text-12 = (
    position: (36.097%, 22.542%),
    body: place(left + bottom, text(size: 1em, fill: color.rgb("#000000"), bottom-edge: "descender", [pass])),
  )

  let stroke-line-13 = (paint: color.luma(0%), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-13 = none
  let line-13 = (data: data.at("line-13"), stroke: stroke-line-13, marker: marker-line-13, transform: transform)

  let stroke-line-14 = (paint: color.luma(0%), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-14 = none
  let line-14 = (data: data.at("line-14"), stroke: stroke-line-14, marker: marker-line-14, transform: transform)

  let legend-style = (
    location: bottom + right,
    title: [test],
    columns: 1,
    row-gutter: 0.5em,
    item-gutter: 0.8em,
    column-gutter: 2.0em,
    handle-length: 2.0em,
    handle-height: 0.7em,
    fill: color.luma(100.0%, 80.0%),
    stroke: color.luma(80.0%, 80.0%),
    frame: block.with(radius: 2.778pt),
  )
  let legend-items = (
    (handle: legend.line2d.with(stroke: stroke-line-7, marker: marker-line-7), label: [line]),
    (
      handle: legend.errorbar.with(
        data: (stroke: stroke-line-0, marker: marker-line-0),
        caps: (left: marker-line-3, right: marker-line-4, bottom: marker-line-5, top: marker-line-6),
        bars: (x: stroke-collection-1, y: stroke-collection-2),
      ),
      label: [parabola],
    ),
  )

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.collection(..collection-1)
  draw.collection(..collection-2)
  draw.line(..line-3)
  draw.line(..line-4)
  draw.line(..line-5)
  draw.line(..line-6)
  draw.line(..line-7)
  draw.line(..line-13)
  draw.line(..line-14)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..title-center)
  draw.text(..title-right)
  draw.text(..label-xaxis)
  draw.text(..label-yaxis)
  draw.text(..text-8)
  draw.text(..text-9)
  draw.text(..text-10)
  draw.text(..text-11)
  draw.text(..text-12)
  legend.legend(..legend-style, ..legend-items)
}


#let grid-0() = {
  let padding = (left: 11.716%, right: 0.694%, top: 6.625%, bottom: 11.861%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    grid(
      columns: (1fr,),
      rows: (1fr,),
      column-gutter: (),
      row-gutter: (),
      axes.cell(position: (0, 0), shape: (1, 1), axes-0()),
    ),
  ))
}
#let figure(width: 15.24cm, height: 10.16cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    fill: color.luma(100.0%),
    stroke: (paint: color.luma(100.0%), thickness: 0.0pt, dash: "solid"),
    { grid-0() },
  )
}

#figure()
