// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *

#set page(width: auto, height: auto, margin: 0.9em)

#let axes-0(xlim: (-0.0995, 2.0895), ylim: (-1.1, 1.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let title-center = (
    position: (50.0%, -5.741%),
    body: place(center + bottom, text(size: 1em + 2.0pt, fill: color.rgb("#000000"), [fill between y1 and 0])),
  )


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let label-xaxis = (
    position: (50.0%, 107.177%),
    body: place(center + top, text(size: 1em, fill: color.rgb("#000000"), [abc...])),
  )

  let xaxis-major-ticks = (
    locs: (-0.25, 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25),
    labels: ($−0.25$, $0.00$, $0.25$, $0.50$, $0.75$, $1.00$, $1.25$, $1.50$, $1.75$, $2.00$, $2.25$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5),
    labels: ($−1.5$, $−1.0$, $−0.5$, $0.0$, $0.5$, $1.0$, $1.5$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let fill-collection-0 = (color.rgb(12.157%, 46.667%, 70.588%),)
  let stroke-collection-0 = (paint: color.luma(10.0%), thickness: 3pt, dash: none)
  let transform-collection-0 = transform
  let compute-scale-collection-0 = compute-scale
  let offset-transform-collection-0 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-0 = (
    data: data.at("collection-0"),
    fill: fill-collection-0,
    stroke: stroke-collection-0,
    transform: transform-collection-0,
    compute-scale: compute-scale-collection-0,
    offset-transform: offset-transform-collection-0,
  )

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.collection(..collection-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..title-center)
  draw.text(..label-xaxis)
}


#let axes-1(xlim: (-0.0995, 2.0895), ylim: (-1.1, 1.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")

  let title-center = (
    position: (50.0%, -5.741%),
    body: place(center + bottom, text(size: 1em + 2.0pt, fill: color.rgb("#000000"), [fill between y1 and 1])),
  )


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-0.25, 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25),
    labels: ($−0.25$, $0.00$, $0.25$, $0.50$, $0.75$, $1.00$, $1.25$, $1.50$, $1.75$, $2.00$, $2.25$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5),
    labels: ($−1.5$, $−1.0$, $−0.5$, $0.0$, $0.5$, $1.0$, $1.5$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let fill-collection-0 = (color.rgb(12.157%, 46.667%, 70.588%),)
  let stroke-collection-0 = (paint: (), thickness: 1.0pt, dash: none)
  let transform-collection-0 = transform
  let compute-scale-collection-0 = compute-scale
  let offset-transform-collection-0 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-0 = (
    data: data.at("collection-0"),
    fill: fill-collection-0,
    stroke: stroke-collection-0,
    transform: transform-collection-0,
    compute-scale: compute-scale-collection-0,
    offset-transform: offset-transform-collection-0,
  )

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.collection(..collection-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..title-center)
}


#let axes-2(xlim: (-0.0995, 2.0895), ylim: (-1.1, 1.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")

  let title-center = (
    position: (50.0%, -5.741%),
    body: place(center + bottom, text(size: 1em + 2.0pt, fill: color.rgb("#000000"), [fill between y1 and y2])),
  )


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 2.0pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let label-xaxis = (
    position: (50.0%, 120.171%),
    body: place(center + top, text(size: 1em, fill: color.rgb("#000000"), [x])),
  )

  let xaxis-major-ticks = (
    locs: (-0.25, 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25),
    labels: ($−0.25$, $0.00$, $0.25$, $0.50$, $0.75$, $1.00$, $1.25$, $1.50$, $1.75$, $2.00$, $2.25$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5),
    labels: ($−1.5$, $−1.0$, $−0.5$, $0.0$, $0.5$, $1.0$, $1.5$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let fill-collection-0 = (color.rgb(12.157%, 46.667%, 70.588%),)
  let stroke-collection-0 = (paint: (), thickness: 1.0pt, dash: none)
  let transform-collection-0 = transform
  let compute-scale-collection-0 = compute-scale
  let offset-transform-collection-0 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-0 = (
    data: data.at("collection-0"),
    fill: fill-collection-0,
    stroke: stroke-collection-0,
    transform: transform-collection-0,
    compute-scale: compute-scale-collection-0,
    offset-transform: offset-transform-collection-0,
  )

  std.place(rect(width: 100%, height: 100%, fill: color.rgb(100.0%, 0.0%, 0.0%)))
  draw.collection(..collection-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..title-center)
  draw.text(..label-xaxis)
}


#let grid-0() = {
  let padding = (left: 7.919%, right: 0.695%, top: 4.417%, bottom: 7.907%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    grid(
      columns: (1fr,),
      rows: (1fr, 1fr, 1fr),
      column-gutter: (),
      row-gutter: (10.472%, 6.753%),
      axes.cell(position: (0, 0), shape: (1, 1), axes-0()),
      axes.cell(position: (0, 1), shape: (1, 1), axes-1()),
      axes.cell(position: (0, 2), shape: (1, 1), axes-2()),
    ),
  ))
}
#let figure(width: 15.24cm, height: 15.24cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    fill: color.luma(100.0%),
    stroke: (paint: color.luma(100.0%), thickness: 0.0pt, dash: "solid"),
    { grid-0() },
  )
}

#figure()
