// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *

#set page(width: auto, height: auto, margin: 0.9em)

#let axes-0(xlim: (-20.5, 20.5), ylim: (-20.5, 20.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let title-center = (
    position: (50.0%, -2.255%),
    body: place(center + bottom, text(size: 1em + 2.0pt, fill: color.rgb("#000000"), [my colormesh])),
  )


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-30.0, -20.0, -10.0, 0.0, 10.0, 20.0, 30.0),
    labels: ($−30$, $−20$, $−10$, $0$, $10$, $20$, $30$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-25.0, -20.0, -15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0, 20.0, 25.0),
    labels: ($−25$, $−20$, $−15$, $−10$, $−5$, $0$, $5$, $10$, $15$, $20$, $25$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let gradient-quad-mesh-0 = gradient.linear(..color.map.viridis)
  let colormap-quad-mesh-0(v, vmin: 0, vmax: 1680) = gradient-quad-mesh-0.sample((v - vmin) / (vmax - vmin) * 100%)
  let quad-mesh-0 = (data: data.at("quad-mesh-0"), colormap: colormap-quad-mesh-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.quad-mesh(..quad-mesh-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..title-center)
}


#let colorbar-1(lim: (0.0, 1680.0)) = {
  let scale = 1 / (lim.at(1) - lim.at(0)) * 100%
  let shift = 50% - (lim.at(0) + lim.at(1)) / 2 * scale

  let transform(point) = {
    let (x, y) = point
    return (0, 100% - (y * scale + shift))
  }

  let label-colormap = (
    position: (373.419%, 50.0%),
    body: rotate(-90.0deg, place(center + top, text(size: 1em, fill: color.rgb("#000000"), [abc]))),
  )

  let colormap-major-ticks = (
    locs: (0.0, 200.0, 400.0, 600.0, 800.0, 1000.0, 1200.0, 1400.0, 1600.0, 1800.0),
    labels: ($0$, $200$, $400$, $600$, $800$, $1000$, $1200$, $1400$, $1600$, $1800$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let gradient = std.gradient.linear(..color.map.viridis, angle: -90deg)

  let stroke = (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")

  std.place(rect(width: 100%, height: 100%, fill: gradient, stroke: stroke))
  axes.yaxis-ticks(show-ticks: (right,), show-labels: (right,), ..colormap-major-ticks, transform)
  draw.text(..label-colormap)
}


#let grid-0() = {
  let padding = (left: 16.75%, right: 18.737%, top: 12.0%, bottom: 11.0%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    grid(
      columns: (0.8fr, 0.15fr),
      rows: (0.0fr, 1.0fr, 0.0fr),
      column-gutter: (6.007%,),
      row-gutter: (),
      axes.cell(position: (0, 0), shape: (1, 3), axes-0()), axes.cell(position: (1, 1), shape: (1, 1), colorbar-1()),
    ),
  ))
}
#let figure(width: 16.256cm, height: 12.192cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    fill: color.luma(100.0%),
    stroke: (paint: color.luma(100.0%), thickness: 0.0pt, dash: "solid"),
    { grid-0() },
  )
}

#figure()
