// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *

#set page(width: auto, height: auto, margin: 0.9em)

#let axes-0(xlim: (-11.0, 11.0), ylim: (-5.823773686072045, 5.823773686072045), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")


  let spines = (left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")), right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")), bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")), top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")))

  let xaxis-major-ticks = (locs: (-12.5, -10.0, -7.5, -5.0, -2.5, 0.0, 2.5, 5.0, 7.5, 10.0, 12.5), labels: ($−12.5$, $−10.0$, $−7.5$, $−5.0$, $−2.5$, $0.0$, $2.5$, $5.0$, $7.5$, $10.0$, $12.5$), tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)), label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))))

  let yaxis-major-ticks = (locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0), labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$), tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)), label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))))

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = markers.caretdown(3.0pt, fill: color.luma(0%), stroke: color.rgb("#1f77b4") + 1.0pt)
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let fill-collection-1 = ()
  let stroke-collection-1 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (data: data.at("collection-1"), fill: fill-collection-1, stroke: stroke-collection-1, transform: transform-collection-1, compute-scale: compute-scale-collection-1, offset-transform: offset-transform-collection-1)

  let stroke-line-2 = (paint: color.rgb("#ff7f0e"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-2 = markers.hexagon1(3.0pt, fill: color.rgb("#ff7f0e"), stroke: color.rgb("#ff7f0e") + 1.0pt)
  let line-2 = (data: data.at("line-2"), stroke: stroke-line-2, marker: marker-line-2, transform: transform)

  let fill-collection-3 = ()
  let stroke-collection-3 = (paint: color.rgb(100.0%, 49.804%, 5.49%), thickness: 1.5pt, dash: none)
  let transform-collection-3 = transform
  let compute-scale-collection-3 = compute-scale
  let offset-transform-collection-3 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-3 = (data: data.at("collection-3"), fill: fill-collection-3, stroke: stroke-collection-3, transform: transform-collection-3, compute-scale: compute-scale-collection-3, offset-transform: offset-transform-collection-3)

  let legend-style = (location: top + left, title: none, columns: 1, row-gutter: 0.5em, item-gutter: 0.8em, column-gutter: 2.0em, handle-length: 2.0em, handle-height: 0.7em, fill: color.luma(100.0%, 80.0%), stroke: color.luma(80.0%, 80.0%), frame: block.with(radius: 2.778pt))
  let legend-items = ((handle: legend.errorbar.with(data: (stroke: stroke-line-0, marker: marker-line-0), caps: (:), bars: (y: stroke-collection-1,)), label: [data-blue]), (handle: legend.errorbar.with(data: (stroke: stroke-line-2, marker: marker-line-2), caps: (:), bars: (y: stroke-collection-3,)), label: [data-orange]))

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.collection(..collection-1)
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  draw.line(..line-2)
  axes.spines(spines)
  legend.legend(..legend-style, ..legend-items)
}


#let grid-0() = {
  let padding = (left: 12.5%, right: 10.0%, top: 12.0%, bottom: 11.0%)
  place(top + left, dx: padding.left, dy: padding.top, block(width: 100% - padding.right - padding.left, height: 100% - padding.top - padding.bottom, fill: none, stroke: none, grid(columns: (1fr,), rows: (1fr,), column-gutter: (), row-gutter: (), axes.cell(position: (0, 0), shape: (1, 1), axes-0()))))
}
#let figure(width: 15.24cm, height: 12.7cm) = {
  show: figure-style
  block(width: width, height: height, fill: color.luma(100.0%), stroke: (paint: color.luma(100.0%), thickness: 0.0pt, dash: "solid"), {grid-0()})
}

#figure()