import pathlib
import textwrap

import matplotlib.figure
import matplotlib.gridspec

from pypst import Binding, Block, Color, Functional, Renderable, ShowRule

from .axes import Axes, ColorbarAxes, InsetAxes
from .grid import AxesGrid
from .text import Text
from .typst import color_from_mpl, Function, Length, Ratio, Stroke


def template(
    width: str,
    height: str,
    fill: Color,
    stroke: Stroke,
    body: str | Renderable | None = None,
) -> str:
    figure = Function(
        name="figure",
        kwargs=dict(width=width, height=height),
    )

    block = Block(
        width="width",
        height="height",
        stroke=stroke,
        fill=fill,
        body=body,
    )
    body = Functional(body=(ShowRule(body="figure-style"), block)).render().lstrip("#")
    return Binding(name=figure, value=body).render() + "\n\n" + "#figure()"


class Figure:
    def __init__(self, fig: matplotlib.figure.Figure):
        self.fig = fig
        self.grids: list[AxesGrid] = []
        self.inset_axes: list[InsetAxes] = []
        self.other_axes: list[Axes] = []
        self.texts: list[Text] = []
        self.definitions: list[Binding] = []
        self.executions: list[tuple[Function, float]] = []
        self.parse()

    @property
    def width(self) -> Length:
        return Length(self.fig.get_figwidth() * 2.54, "cm")

    @property
    def height(self) -> Length:
        return Length(self.fig.get_figheight() * 2.54, "cm")

    @property
    def fill(self) -> Color:
        return color_from_mpl(self.fig.get_facecolor())

    @property
    def stroke(self) -> Stroke:
        return Stroke.from_mpl(
            edgecolor=self.fig.get_edgecolor(),
            linewidth=self.fig.get_linewidth(),
            linestyle="solid",
        )

    @staticmethod
    def render_definitions(definitions: list[Binding | None]) -> list[str]:
        rendered: list[str] = []
        for definition in definitions:
            rendered.append(definition.render().lstrip("#"))
        return rendered

    @staticmethod
    def render_executions(executions: list[tuple[Function, float]]) -> list[str]:
        rendered: list[str] = []
        for execution, _ in sorted(executions, key=lambda x: x[1]):
            rendered.append(execution.render())
        return rendered

    def transform_point(
        self,
        point,
        transform,
    ) -> str | Renderable | tuple[str | Renderable, str | Renderable]:
        """
        Transform a point from any coordinates to relative figure coordinates.

        In Typst, the relative figure coordinates range from 0% to 100% in both
        directions, although the y-axis is inverted compared to matplotlib.
        """
        x, y = point
        if transform == self.fig.transFigure:
            return Ratio((x, 1 - y))
        else:
            x, y = self.fig.transFigure.inverted().transform_point(
                transform.transform_point(point)
            )
            return Ratio((x, 1 - y))

    def parse(self) -> None:
        grid_axes: list[list[Axes]] = []
        gridspecs: list[matplotlib.gridspec.GridSpec] = []
        for i, ax in enumerate(self.fig.get_axes()):
            name = str(i)
            gs = ax.get_gridspec()
            standalone = gs is None

            if hasattr(ax, "_colorbar"):
                axes = ColorbarAxes(ax, name, prefix="colorbar", standalone=standalone)
            else:
                axes = Axes(ax, name, standalone=standalone)

            if gs is None:
                self.other_axes.append(axes)
            else:
                if gs not in gridspecs:
                    gridspecs.append(gs)
                    grid_axes.append([axes])
                else:
                    grid_axes[gridspecs.index(gs)].append(axes)

            for ix in ax.child_axes:
                inset_axes = InsetAxes(ix, axes, str(len(self.inset_axes)))
                self.inset_axes.append(inset_axes)
                axes.inset_axes.append(inset_axes)

        for i in range(len(gridspecs)):
            self.grids.append(AxesGrid(gridspecs[i], grid_axes[i], str(i)))

        for i, text in enumerate(self.fig.texts):
            if text.get_text():
                self.texts.append(Text(text, self, name=str(i)))

    def render(self, path: str | pathlib.Path, header: str | None = None) -> None:
        path = pathlib.Path(path)
        path.mkdir(parents=True, exist_ok=True)
        path.joinpath("data").mkdir(parents=True, exist_ok=True)

        if header is None:
            header: str = textwrap.dedent("""\
            #import "/mpl2typ/lib.typ": *
            #import "/style.typ": *
            """)

        with open(path.joinpath("figure.typ"), "w", encoding="utf-8") as f:
            f.write(
                "// This file is automatically generated by some development version of mpl2typ\n"
            )
            f.write(header + "\n")

            children: list[str] = []
            for inset in self.inset_axes:
                f.write(inset.render(path) + "\n")

            for grid in self.grids:
                for ax in grid.axes:
                    f.write(ax.render(path) + "\n")
                f.write(grid.render() + "\n\n")
                children.append(f"{grid.name}()")

            for ax in self.other_axes:
                f.write(ax.render(path) + "\n")
                name = ax.name
                if ax.standalone:
                    name = "standalone-" + name
                children.append(f"{name}()")

            for text in self.texts:
                self.definitions.append(text.definition)
                self.executions.append((text.execution, text.zorder))

            if self.definitions:
                children.append("\n".join(self.render_definitions(self.definitions)))
            if self.executions:
                children.append("\n".join(self.render_executions(self.executions)))

            f.write(
                template(
                    width=self.width,
                    height=self.height,
                    fill=self.fill,
                    stroke=self.stroke,
                    body=Functional(children),
                )
            )
