// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *

#set page(width: auto, height: auto, margin: 0.9em)

#let axes-0(xlim: (-1.0, 2.0), ylim: (-1.0, 2.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let label-xaxis = (
    position: (50.0%, 107.605%),
    body: place(center + top, text(size: 1em, fill: color.rgb("#000000"), [x])),
  )

  let xaxis-major-ticks = (
    locs: (-1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0),
    labels: ($−1.0$, $−0.5$, $0.0$, $0.5$, $1.0$, $1.5$, $2.0$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
    grid-style: (
      stroke: (
        paint: color.luma(0%, 100.0%),
        thickness: 0.8pt,
        cap: "butt",
        join: "round",
        dash: (array: (4.8pt, 2.4pt, 0.8pt, 2.4pt), phase: 0.0pt),
      ),
    ),
  )

  let yaxis-major-ticks = (
    locs: (-1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0),
    labels: ($−1.0$, $−0.5$, $0.0$, $0.5$, $1.0$, $1.5$, $2.0$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
    grid-style: (
      stroke: (
        paint: color.luma(0%, 100.0%),
        thickness: 0.8pt,
        cap: "butt",
        join: "round",
        dash: (array: (4.8pt, 2.4pt, 0.8pt, 2.4pt), phase: 0.0pt),
      ),
    ),
  )

  let fill-collection-0 = (color.rgb(100.0%, 0.0%, 0.0%),)
  let stroke-collection-0 = (paint: color.luma(0.0%), thickness: 2pt, dash: (array: (12pt, 6pt, 2pt, 6pt), phase: 0pt))
  let transform-collection-0 = point => {
    let (x, y) = point
    ((x * 1.0 + 0.0) * 1pt, (y * 1.0 + 0.0) * -1pt)
  }
  let compute-scale-collection-0 = size => calc.sqrt(size)
  let offset-transform-collection-0 = transform
  let collection-0 = (
    data: data.at("collection-0"),
    fill: fill-collection-0,
    stroke: stroke-collection-0,
    transform: transform-collection-0,
    compute-scale: compute-scale-collection-0,
    offset-transform: offset-transform-collection-0,
  )

  let text-1 = (
    position: transform((1, 1)),
    body: place(left + bottom, text(size: 1em, fill: color.rgb("#000000"), [abc])),
  )

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.collection(..collection-0)
  axes.xaxis-grid(..xaxis-major-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-grid(..yaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  draw.text(..label-xaxis)
  draw.text(..text-1)
}


#let grid-0() = {
  let padding = (left: 12.5%, right: 10.0%, top: 12.0%, bottom: 11.0%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    grid(
      columns: (1fr,),
      rows: (1fr,),
      column-gutter: (),
      row-gutter: (),
      axes.cell(position: (0, 0), shape: (1, 1), axes-0()),
    ),
  ))
}
#let figure(width: 15.24cm, height: 12.7cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    fill: color.luma(100.0%),
    stroke: (paint: color.luma(100.0%), thickness: 0.0pt, dash: "solid"),
    { grid-0() },
  )
}

#figure()
