// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *

#set page(width: auto, height: auto, margin: 0.9em)

#let axes-0(xlim: (-0.65, 13.65), ylim: (-1.1762813728785546, 3.196246241817512), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")


  let spines = (
    left: (bounds: (100.0%, -0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, -0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-2.0, 0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0),
    labels: ($−2$, $0$, $2$, $4$, $6$, $8$, $10$, $12$, $14$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
    grid-style: (
      stroke: (paint: color.luma(90.0%, 100.0%), thickness: 0.8pt, cap: "butt", join: "round", dash: "solid"),
    ),
  )

  let yaxis-major-ticks = (
    locs: (-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5),
    labels: ($−1.5$, $−1.0$, $−0.5$, $0.0$, $0.5$, $1.0$, $1.5$, $2.0$, $2.5$, $3.0$, $3.5$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = none
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let stroke-line-1 = (
    paint: color.rgb("#808080").transparentize(70.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-1 = markers.circle(
    3.0pt,
    fill: color.rgb("#808080").transparentize(70.0%),
    stroke: color.rgb("#808080").transparentize(70.0%) + 1.0pt,
  )
  let line-1 = (data: data.at("line-1"), stroke: stroke-line-1, marker: marker-line-1, transform: transform)

  let stroke-line-2 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-2 = none
  let line-2 = (data: data.at("line-2"), stroke: stroke-line-2, marker: marker-line-2, transform: transform)

  let stroke-line-3 = (
    paint: color.rgb("#808080").transparentize(70.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-3 = markers.circle(
    3.0pt,
    fill: color.rgb("#808080").transparentize(70.0%),
    stroke: color.rgb("#808080").transparentize(70.0%) + 1.0pt,
  )
  let line-3 = (data: data.at("line-3"), stroke: stroke-line-3, marker: marker-line-3, transform: transform)

  let stroke-line-4 = (paint: color.rgb("#ff7f0e"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-4 = none
  let line-4 = (data: data.at("line-4"), stroke: stroke-line-4, marker: marker-line-4, transform: transform)

  let stroke-line-5 = (
    paint: color.rgb("#808080").transparentize(70.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-5 = markers.circle(
    3.0pt,
    fill: color.rgb("#808080").transparentize(70.0%),
    stroke: color.rgb("#808080").transparentize(70.0%) + 1.0pt,
  )
  let line-5 = (data: data.at("line-5"), stroke: stroke-line-5, marker: marker-line-5, transform: transform)

  let legend-style = (
    location: top + left,
    title: [Parameter where:],
    columns: 1,
    row-gutter: 0.5em,
    item-gutter: 0.8em,
    column-gutter: 2.0em,
    handle-length: 2.0em,
    handle-height: 0.7em,
    fill: color.luma(100.0%, 80.0%),
    stroke: color.luma(80.0%, 80.0%),
    frame: block.with(radius: 2.778pt),
  )
  let legend-items = (
    (handle: legend.line2d.with(stroke: stroke-line-0, marker: marker-line-0), label: [pre (default)]),
    (handle: legend.line2d.with(stroke: stroke-line-2, marker: marker-line-2), label: [mid]),
    (handle: legend.line2d.with(stroke: stroke-line-4, marker: marker-line-4), label: [post]),
  )

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  draw.line(..line-1)
  draw.line(..line-2)
  draw.line(..line-3)
  draw.line(..line-4)
  draw.line(..line-5)
  axes.xaxis-grid(..xaxis-major-ticks, transform)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
  legend.legend(..legend-style, ..legend-items)
}


#let grid-0() = {
  let padding = (left: 12.5%, right: 10.0%, top: 12.0%, bottom: 11.0%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    grid(
      columns: (1fr,),
      rows: (1fr,),
      column-gutter: (),
      row-gutter: (),
      axes.cell(position: (0, 0), shape: (1, 1), axes-0()),
    ),
  ))
}
#let figure(width: 16.256cm, height: 12.192cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    fill: color.luma(100.0%),
    stroke: (paint: color.luma(100.0%), thickness: 0.0pt, dash: "solid"),
    { grid-0() },
  )
}

#figure()
