// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *

#set page(width: auto, height: auto, margin: 0.9em)

#let axes-0(xlim: (-5.5, 5.5), ylim: (-5.5, 5.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let axes-1(xlim: (-5.5, 5.5), ylim: (-1.25, 26.25), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-10.0, 0.0, 10.0, 20.0, 30.0),
    labels: ($−10$, $0$, $10$, $20$, $30$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let axes-2(xlim: (-5.5, 5.5), ylim: (-137.5, 137.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-200.0, -100.0, 0.0, 100.0, 200.0),
    labels: ($−200$, $−100$, $0$, $100$, $200$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let grid-0() = {
  let padding = (left: 5.0%, right: 62.0%, top: 2.0%, bottom: 6.0%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    grid(
      columns: (1fr, 1fr),
      rows: (1fr, 1fr, 1fr),
      column-gutter: (14.891%,),
      row-gutter: (5.883%,),
      axes.cell(position: (0, 0), shape: (2, 2), axes-0()),
      axes.cell(position: (0, 2), shape: (1, 1), axes-1()),
      axes.cell(position: (1, 2), shape: (1, 1), axes-2()),
    ),
  ))
}
#let axes-3(xlim: (-5.5, 5.5), ylim: (0.945, 1.0550000000000002), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-3.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (0.9400000000000001, 0.9600000000000001, 0.9800000000000001, 1.0, 1.02, 1.04, 1.06),
    labels: ($0.94$, $0.96$, $0.98$, $1.00$, $1.02$, $1.04$, $1.06$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let axes-4(xlim: (-5.5, 5.5), ylim: (-5.5, 5.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-4.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let axes-5(xlim: (-5.5, 5.5), ylim: (-1.25, 26.25), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-5.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-5.0, 0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0),
    labels: ($−5$, $0$, $5$, $10$, $15$, $20$, $25$, $30$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let axes-6(xlim: (-5.5, 5.5), ylim: (-137.5, 137.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-6.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-150.0, -100.0, -50.0, 0.0, 50.0, 100.0, 150.0),
    labels: ($−150$, $−100$, $−50$, $0$, $50$, $100$, $150$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let axes-7(xlim: (-5.5, 5.5), ylim: (-31.25, 656.25), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-7.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-100.0, 0.0, 100.0, 200.0, 300.0, 400.0, 500.0, 600.0, 700.0),
    labels: ($−100$, $0$, $100$, $200$, $300$, $400$, $500$, $600$, $700$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let axes-8(xlim: (-5.5, 5.5), ylim: (-3437.5, 3437.5), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-8.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-4000.0, -3000.0, -2000.0, -1000.0, 0.0, 1000.0, 2000.0, 3000.0, 4000.0),
    labels: ($−4000$, $−3000$, $−2000$, $−1000$, $0$, $1000$, $2000$, $3000$, $4000$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (
    paint: color.rgb("#1f77b4").transparentize(50.0%),
    thickness: 1.5pt,
    cap: "butt",
    join: "round",
    dash: (array: (5.55pt, 2.4pt), phase: 0.0pt),
  )
  let marker-line-0 = markers.circle(
    3.0pt,
    fill: color.rgb("#1f77b4").transparentize(50.0%),
    stroke: color.luma(0%, 50.0%) + 1.0pt,
  )
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}


#let grid-1() = {
  let padding = (left: 45.0%, right: 2.0%, top: 2.0%, bottom: 6.0%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    grid(
      columns: (1fr, 1fr, 1fr),
      rows: (1fr, 1fr),
      column-gutter: (9.46%, 9.46%),
      row-gutter: (9.091%,),
      axes.cell(position: (0, 0), shape: (1, 1), axes-3()),
      axes.cell(position: (0, 1), shape: (1, 1), axes-4()),
      axes.cell(position: (1, 0), shape: (1, 1), axes-5()),
      axes.cell(position: (1, 1), shape: (1, 1), axes-6()),
      axes.cell(position: (2, 0), shape: (1, 1), axes-7()),
      axes.cell(position: (2, 1), shape: (1, 1), axes-8()),
    ),
  ))
}
#let figure(width: 22.86cm, height: 12.7cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    fill: color.luma(100.0%),
    stroke: (paint: color.luma(100.0%), thickness: 0.0pt, dash: "solid"),
    {
      grid-0()
      grid-1()
    },
  )
}

#figure()
