// This file is automatically generated by some development version of mpl2typ
#import "/mpl2typ/lib.typ": *
#import "/style.typ": *

#set page(width: auto, height: auto, margin: 0.9em)

#let axes-0(xlim: (-5.5, 5.5), ylim: (-1.1, 1.1), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-0.json")

  let title-center = (
    position: (50.0%, -5.257%),
    body: place(center + bottom, text(size: 1em + 2.0pt, fill: color.rgb("#000000"), [Hello World $a^2$])),
  )


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let xaxis-minor-ticks = (
    locs: (-5.0, -3.0, -1.0, 1.0, 3.0, 5.0),
    labels: (),
    tick-style: (direction: "out", line: (length: 2.0pt, angle: 90deg, stroke: color.rgb("#000000") + 0.6pt)),
    label-style: (pad: 3.4pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5),
    labels: ($−1.5$, $−1.0$, $−0.5$, $0.0$, $0.5$, $1.0$, $1.5$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = none
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let fill-collection-1 = ()
  let stroke-collection-1 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: color.rgb("#ff7f0e").transparentize(30.0%),
    thickness: 3.0pt,
    cap: "butt",
    join: "round",
    dash: (array: (12.0pt, 3.0pt), phase: 2.7pt),
  )
  let marker-line-2 = markers.octagon(
    3.0pt,
    fill: color.rgb("#ff7f0e").transparentize(30.0%),
    stroke: color.luma(0%, 70.0%) + 0.9pt,
  )
  let line-2 = (data: data.at("line-2"), stroke: stroke-line-2, marker: marker-line-2, transform: transform)

  let fill-collection-3 = (color.rgb(100.0%, 0.0%, 0.0%),)
  let stroke-collection-3 = (paint: color.rgb(100.0%, 0.0%, 0.0%), thickness: 1.0pt, dash: none)
  let transform-collection-3 = point => {
    let (x, y) = point
    ((x * 1.0 + 0.0) * 1pt, (y * 1.0 + 0.0) * -1pt)
  }
  let compute-scale-collection-3 = size => calc.sqrt(size)
  let offset-transform-collection-3 = transform
  let collection-3 = (
    data: data.at("collection-3"),
    fill: fill-collection-3,
    stroke: stroke-collection-3,
    transform: transform-collection-3,
    compute-scale: compute-scale-collection-3,
    offset-transform: offset-transform-collection-3,
  )

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.collection(..collection-3)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
  draw.text(..title-center)
}


#let axes-1(xlim: (-5.5, 5.5), ylim: (-6.6, 6.6), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-1.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let xaxis-minor-ticks = (
    locs: (-5.0, -3.0, -1.0, 1.0, 3.0, 5.0),
    labels: (),
    tick-style: (direction: "out", line: (length: 2.0pt, angle: 90deg, stroke: color.rgb("#000000") + 0.6pt)),
    label-style: (pad: 3.4pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-10.0, -5.0, 0.0, 5.0, 10.0),
    labels: ($−10$, $−5$, $0$, $5$, $10$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = none
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let fill-collection-1 = ()
  let stroke-collection-1 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: color.rgb("#ff7f0e").transparentize(30.0%),
    thickness: 3.0pt,
    cap: "butt",
    join: "round",
    dash: (array: (12.0pt, 3.0pt), phase: 2.7pt),
  )
  let marker-line-2 = markers.octagon(
    3.0pt,
    fill: color.rgb("#ff7f0e").transparentize(30.0%),
    stroke: color.luma(0%, 70.0%) + 0.9pt,
  )
  let line-2 = (data: data.at("line-2"), stroke: stroke-line-2, marker: marker-line-2, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let axes-2(xlim: (-5.5, 5.5), ylim: (-27.6, 29.6), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-2.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let xaxis-minor-ticks = (
    locs: (-5.0, -3.0, -1.0, 1.0, 3.0, 5.0),
    labels: (),
    tick-style: (direction: "out", line: (length: 2.0pt, angle: 90deg, stroke: color.rgb("#000000") + 0.6pt)),
    label-style: (pad: 3.4pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-40.0, -20.0, 0.0, 20.0, 40.0),
    labels: ($−40$, $−20$, $0$, $20$, $40$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = none
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let fill-collection-1 = ()
  let stroke-collection-1 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: color.rgb("#ff7f0e").transparentize(30.0%),
    thickness: 3.0pt,
    cap: "butt",
    join: "round",
    dash: (array: (12.0pt, 3.0pt), phase: 2.7pt),
  )
  let marker-line-2 = markers.octagon(
    3.0pt,
    fill: color.rgb("#ff7f0e").transparentize(30.0%),
    stroke: color.luma(0%, 70.0%) + 0.9pt,
  )
  let line-2 = (data: data.at("line-2"), stroke: stroke-line-2, marker: marker-line-2, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let axes-3(xlim: (-5.5, 5.5), ylim: (-140.8, 140.8), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-3.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let xaxis-minor-ticks = (
    locs: (-5.0, -3.0, -1.0, 1.0, 3.0, 5.0),
    labels: (),
    tick-style: (direction: "out", line: (length: 2.0pt, angle: 90deg, stroke: color.rgb("#000000") + 0.6pt)),
    label-style: (pad: 3.4pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-200.0, -100.0, 0.0, 100.0, 200.0),
    labels: ($−200$, $−100$, $0$, $100$, $200$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = none
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let fill-collection-1 = ()
  let stroke-collection-1 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: color.rgb("#ff7f0e").transparentize(30.0%),
    thickness: 3.0pt,
    cap: "butt",
    join: "round",
    dash: (array: (12.0pt, 3.0pt), phase: 2.7pt),
  )
  let marker-line-2 = markers.octagon(
    3.0pt,
    fill: color.rgb("#ff7f0e").transparentize(30.0%),
    stroke: color.luma(0%, 70.0%) + 0.9pt,
  )
  let line-2 = (data: data.at("line-2"), stroke: stroke-line-2, marker: marker-line-2, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let axes-4(xlim: (-5.5, 5.5), ylim: (-687.7, 691.7), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-4.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let xaxis-minor-ticks = (
    locs: (-5.0, -3.0, -1.0, 1.0, 3.0, 5.0),
    labels: (),
    tick-style: (direction: "out", line: (length: 2.0pt, angle: 90deg, stroke: color.rgb("#000000") + 0.6pt)),
    label-style: (pad: 3.4pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-1000.0, -500.0, 0.0, 500.0, 1000.0),
    labels: ($−1000$, $−500$, $0$, $500$, $1000$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = none
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let fill-collection-1 = ()
  let stroke-collection-1 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: color.rgb("#ff7f0e").transparentize(30.0%),
    thickness: 3.0pt,
    cap: "butt",
    join: "round",
    dash: (array: (12.0pt, 3.0pt), phase: 2.7pt),
  )
  let marker-line-2 = markers.octagon(
    3.0pt,
    fill: color.rgb("#ff7f0e").transparentize(30.0%),
    stroke: color.luma(0%, 70.0%) + 0.9pt,
  )
  let line-2 = (data: data.at("line-2"), stroke: stroke-line-2, marker: marker-line-2, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let axes-5(xlim: (-5.5, 5.5), ylim: (-3443.0, 3443.0), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-5.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let xaxis-minor-ticks = (
    locs: (-5.0, -3.0, -1.0, 1.0, 3.0, 5.0),
    labels: (),
    tick-style: (direction: "out", line: (length: 2.0pt, angle: 90deg, stroke: color.rgb("#000000") + 0.6pt)),
    label-style: (pad: 3.4pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-4000.0, -2000.0, 0.0, 2000.0, 4000.0),
    labels: ($−4000$, $−2000$, $0$, $2000$, $4000$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = none
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  let fill-collection-1 = ()
  let stroke-collection-1 = (paint: color.rgb(12.157%, 46.667%, 70.588%), thickness: 1.5pt, dash: none)
  let transform-collection-1 = transform
  let compute-scale-collection-1 = compute-scale
  let offset-transform-collection-1 = point => {
    let (x, y) = point
    ((x * 0.01 + 0.0) * 72pt, (y * 0.01 + 0.0) * -72pt)
  }
  let collection-1 = (
    data: data.at("collection-1"),
    fill: fill-collection-1,
    stroke: stroke-collection-1,
    transform: transform-collection-1,
    compute-scale: compute-scale-collection-1,
    offset-transform: offset-transform-collection-1,
  )

  let stroke-line-2 = (
    paint: color.rgb("#ff7f0e").transparentize(30.0%),
    thickness: 3.0pt,
    cap: "butt",
    join: "round",
    dash: (array: (12.0pt, 3.0pt), phase: 2.7pt),
  )
  let marker-line-2 = markers.octagon(
    3.0pt,
    fill: color.rgb("#ff7f0e").transparentize(30.0%),
    stroke: color.luma(0%, 70.0%) + 0.9pt,
  )
  let line-2 = (data: data.at("line-2"), stroke: stroke-line-2, marker: marker-line-2, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-minor-ticks, transform)
  draw.collection(..collection-1)
  draw.line(..line-2)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  draw.line(..line-0)
  axes.spines(spines)
}


#let grid-0() = {
  let padding = (left: 12.5%, right: 10.0%, top: 12.0%, bottom: 11.0%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    grid(
      columns: (1fr, 1fr),
      rows: (1fr, 1fr, 1fr),
      column-gutter: (9.092%,),
      row-gutter: (5.882%, 5.882%),
      axes.cell(position: (0, 0), shape: (1, 1), axes-0()),
      axes.cell(position: (1, 0), shape: (1, 1), axes-1()),
      axes.cell(position: (0, 1), shape: (1, 1), axes-2()),
      axes.cell(position: (1, 1), shape: (1, 1), axes-3()),
      axes.cell(position: (0, 2), shape: (1, 1), axes-4()),
      axes.cell(position: (1, 2), shape: (1, 1), axes-5()),
    ),
  ))
}
#let axes-6(xlim: (-5.5, 5.5), ylim: (-2.8, 36.8), dpi: 100.0) = {
  let xscale = 1 / (xlim.at(1) - xlim.at(0)) * 100%
  let yscale = 1 / (ylim.at(1) - ylim.at(0)) * 100%
  let xshift = 50% - (xlim.at(0) + xlim.at(1)) / 2 * xscale
  let yshift = 50% - (ylim.at(0) + ylim.at(1)) / 2 * yscale

  let transform(point) = {
    let (x, y) = point
    return (x * xscale + xshift, 100% - (y * yscale + yshift))
  }

  let compute-scale(size) = calc.sqrt(size) * dpi / 72

  let data = json("data/axes-6.json")


  let spines = (
    left: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    right: (bounds: (100.0%, 0.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    bottom: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
    top: (bounds: (0.0%, 100.0%), stroke: (paint: color.luma(0.0%), thickness: 0.8pt, dash: "solid")),
  )

  let xaxis-major-ticks = (
    locs: (-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0),
    labels: ($−6$, $−4$, $−2$, $0$, $2$, $4$, $6$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 90deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let yaxis-major-ticks = (
    locs: (-10.0, 0.0, 10.0, 20.0, 30.0, 40.0),
    labels: ($−10$, $0$, $10$, $20$, $30$, $40$),
    tick-style: (direction: "out", line: (length: 3.5pt, angle: 0deg, stroke: color.rgb("#000000") + 0.8pt)),
    label-style: (pad: 3.5pt, rotation: -0.0deg, text: (size: 1em, fill: color.rgb("#000000"))),
  )

  let stroke-line-0 = (paint: color.rgb("#1f77b4"), thickness: 1.5pt, cap: "butt", join: "round", dash: "solid")
  let marker-line-0 = markers.octagon(3.0pt, fill: color.rgb("#1f77b4"), stroke: color.rgb("#1f77b4") + 1.0pt)
  let line-0 = (data: data.at("line-0"), stroke: stroke-line-0, marker: marker-line-0, transform: transform)

  std.place(rect(width: 100%, height: 100%, fill: color.luma(100.0%)))
  draw.line(..line-0)
  axes.xaxis-ticks(show-ticks: (bottom,), show-labels: (bottom,), ..xaxis-major-ticks, transform)
  axes.yaxis-ticks(show-ticks: (left,), show-labels: (left,), ..yaxis-major-ticks, transform)
  axes.spines(spines)
}

#let standalone-axes-6() = {
  let padding = (left: 36.0%, right: 34.0%, top: 20.0%, bottom: 50.0%)
  place(top + left, dx: padding.left, dy: padding.top, block(
    width: 100% - padding.right - padding.left,
    height: 100% - padding.top - padding.bottom,
    fill: none,
    stroke: none,
    axes-6(),
  ))
}
#let figure(width: 25.4cm, height: 17.78cm) = {
  show: figure-style
  block(
    width: width,
    height: height,
    fill: color.luma(100.0%),
    stroke: (paint: color.rgb(100.0%, 0.0%, 0.0%), thickness: 2.0pt, dash: "solid"),
    {
      grid-0()
      standalone-axes-6()
    },
  )
}

#figure()
